# Generated by Django 2.0.5 on 2018-05-27 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrandProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=100)),
                ('childcid', models.CharField(max_length=10)),
                ('productid', models.CharField(max_length=10)),
                ('longname', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=10)),
                ('marketprice', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_brand_product',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('isSelected', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'axf_cart',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='收件人')),
                ('phone', models.CharField(max_length=12, verbose_name='收件人电话')),
                ('address_detail', models.TextField(default='', verbose_name='收货地址')),
            ],
            options={
                'db_table': 'axf_address',
            },
        ),
        migrations.CreateModel(
            name='FoodType',
            fields=[
                ('typeid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('typename', models.CharField(max_length=50)),
                ('childtypenames', models.CharField(max_length=200)),
                ('typesort', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'axf_foodtypes',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('productid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('productimg', models.CharField(max_length=300)),
                ('productname', models.CharField(max_length=100)),
                ('productlongname', models.CharField(max_length=100)),
                ('isxf', models.BooleanField(default=1)),
                ('pmdesc', models.IntegerField(default=1)),
                ('specifics', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('marketprice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('categoryid', models.IntegerField(default=0)),
                ('childcid', models.IntegerField(default=0)),
                ('childcidname', models.CharField(max_length=100)),
                ('dealerid', models.CharField(max_length=10)),
                ('storenums', models.IntegerField(default=1)),
                ('productnum', models.BigIntegerField(default=0)),
            ],
            options={
                'db_table': 'axf_goods',
            },
        ),
        migrations.CreateModel(
            name='MainShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('categoryid', models.CharField(max_length=10)),
                ('brandname', models.CharField(max_length=20)),
                ('img1', models.CharField(max_length=100)),
                ('childcid1', models.CharField(max_length=10)),
                ('productid1', models.CharField(max_length=10)),
                ('longname1', models.CharField(max_length=50)),
                ('price1', models.CharField(max_length=10)),
                ('marketprice1', models.CharField(max_length=10)),
                ('img2', models.CharField(max_length=100)),
                ('childcid2', models.CharField(max_length=10)),
                ('productid2', models.CharField(max_length=10)),
                ('longname2', models.CharField(max_length=50)),
                ('price2', models.CharField(max_length=10)),
                ('marketprice2', models.CharField(max_length=10)),
                ('img3', models.CharField(max_length=100)),
                ('childcid3', models.CharField(max_length=10)),
                ('productid3', models.CharField(max_length=10)),
                ('longname3', models.CharField(max_length=50)),
                ('price3', models.CharField(max_length=10)),
                ('marketprice3', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'axf_mainshow',
            },
        ),
        migrations.CreateModel(
            name='MainShowBrand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trackid', models.CharField(max_length=10)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('categoryid', models.CharField(max_length=10)),
                ('brandname', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'axf_brand',
            },
        ),
        migrations.CreateModel(
            name='MustBuy',
            fields=[
                ('trackid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'axf_mustbuy',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderNum', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单号')),
                ('orderPrice', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payState', models.IntegerField(choices=[(0, '待支付'), (1, '已支付'), (2, '正在支付中'), (3, '已退款')], default=0)),
                ('payType', models.IntegerField(choices=[(0, '余款'), (1, '支付宝'), (2, '微信')], default=0)),
                ('orderState', models.IntegerField(choices=[(0, '待派送'), (1, '已派送'), (2, '已到达'), (3, '已签收'), (4, '拒收'), (5, '未到达')], default=0)),
                ('orderTime', models.DateTimeField(auto_now_add=True)),
                ('orderLastTime', models.DateTimeField(auto_now=True)),
                ('orderAdress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.DeliveryAddress')),
            ],
            options={
                'db_table': 'axf_order',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='小计')),
                ('goods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainapp.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Order')),
            ],
            options={
                'db_table': 'axf_order_goods',
            },
        ),
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('trackid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'axf_nav',
            },
        ),
        migrations.CreateModel(
            name='TopShop',
            fields=[
                ('trackid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
                ('position', models.IntegerField(default=1)),
            ],
            options={
                'db_table': 'axf_shop',
            },
        ),
        migrations.CreateModel(
            name='TopWheel',
            fields=[
                ('trackid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('img', models.CharField(max_length=300)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'axf_wheel',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userPasswd', models.CharField(max_length=32)),
                ('phone', models.CharField(max_length=12)),
                ('address', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=50)),
                ('nickName', models.CharField(max_length=50, verbose_name='昵称')),
                ('imgPath', models.CharField(default='', max_length=100)),
                ('token', models.CharField(default='', max_length=32)),
                ('state', models.BooleanField(default=True, verbose_name='用户状态')),
                ('money', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
            options={
                'db_table': 'axf_user',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.User'),
        ),
        migrations.AddField(
            model_name='deliveryaddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.User'),
        ),
        migrations.AddField(
            model_name='cart',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Goods'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.User'),
        ),
        migrations.AddField(
            model_name='brandproduct',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.MainShowBrand'),
        ),
    ]
