# Generated by Django 2.0.5 on 2018-05-27 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topmenu',
            name='position',
        ),
        migrations.RemoveField(
            model_name='topshop',
            name='position',
        ),
    ]
