# Generated by Django 2.0.5 on 2018-05-27 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20180527_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mustbuy',
            name='position',
        ),
    ]
