# Generated by Django 2.0.5 on 2018-05-27 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_mustbuy_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='mustbuy',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topmenu',
            name='position',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topshop',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
